cp -Rf $1/bin $2/.
cp -Rf $1/classes $2/.
cp -Rf $1/lib $2/.
cp -Rf $1/resource $2/.
cp -Rf $1/docs $2/.
cp -f $1/*.sh $2/.
cp -f $1/*.bat $2/.
cp -f $2/conf/config.ini $1/conf/config.ini
cp -f $1/conf $2/.
